djanglavel/notebook/urls.py
from django.conf.urls import url

from .views import index, ContactListView, ContactDetailView
from .views import ContactUpdateView, ContactCreateView, ContactDeleteView

urlpatterns = [
    url(r'^oldindex/$', index, name='index'),
    url(r'^contact/$', ContactListView.as_view(), name='list'),
    url(r'^contact/(?P<slug>[-\w\d]+)/$', ContactDetailView.as_view(), name='detail'),
    url(r'^contact/(?P<slug>[-\w\d]+)/update$', ContactUpdateView.as_view(), name='update'),
    url(r'^contact/(?P<slug>[-\w\d]+)/delete$', ContactDeleteView.as_view(), name='delete'),
    url(r'^contact/new$', ContactCreateView.as_view(), name='create'),
]

djanglavel/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^notebook/', include('djanglavel.notebook.urls', namespace="notebook")),
    url(r'^admin/', include(admin.site.urls)),
]

djanglavel/notebook/models.py
from django.db import models
from autoslug import AutoSlugField


class Contact(models.Model):

    """Contact in a Notebook"""
    first_name = models.CharField('Firstname', max_length=200)
    last_name = models.CharField('Lastname', max_length=200)
    birthday = models.DateField('Birthday')

    # Example of third party module : use a slug instead of id for URLs
    def get_full_name(self):
        """get full name for display or slugify"""
        return "%s %s" % (self.first_name, self.last_name)

    slug = AutoSlugField('Slug', unique=True, populate_from=get_full_name)

    def get_absolute_url(self):
        # Must import here to avoid circular imports
        from django.core.urlresolvers import reverse
        return reverse('notebook:detail', args=[self.slug])


class Email(models.Model):

    """Email for a Contact"""
    contact = models.ForeignKey(Contact)
    email = models.EmailField()

djanglavel/notebook/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy


from .models import Contact


def index(request):
    """Old style view : just to show how it was done before
    """
    result = {}
    result["contacts"] = Contact.objects.all()
    return render(request, 'notebook/index.html', result)

# Class based views : Easy to write, easy to tweak.


class ContactListView(ListView):

    model = Contact
    context_object_name = "contacts"


class ContactDetailView(DetailView):

    model = Contact
    context_object_name = "contact"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ContactDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all emails
        context['emails'] = self.object.email_set.all()
        return context


class ContactCreateView(CreateView):

    model = Contact
    fields = ["first_name", "last_name", "birthday"]


class ContactUpdateView(UpdateView):

    model = Contact
    fields = ["first_name", "last_name", "birthday"]


class ContactDeleteView(DeleteView):

    model = Contact
    success_url = reverse_lazy("notebook:list")

djanglavel/notebook/templates/notebook/base.html
<!DOCTYPE html>{% load bootstrap3 %}
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Notebook - {% block title%}{% endblock title %}</title>

    <!-- Bootstrap -->
    {% bootstrap_css %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      {% block content %}{% endblock content %}
    </div>
    {% bootstrap_javascript %}
  </body>

</html>

djanglavel/notebook/templates/notebook/contact_confirm_delete.html
{% extends "notebook/base.html" %}{% load bootstrap3 %}
{% block title %}Contact Delete{% endblock title %}
{% block content %}
<form action="{% url 'notebook:delete' slug=object.slug %}" method="post" class="form">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object.get_full_name }}"?</p>
  {% buttons %}
    <button type="submit" class="btn btn-danger">
      {% bootstrap_icon "trash" %} Submit
    </button>
  {% endbuttons %}
</form>
{% endblock content %}

djanglavel/notebook/templates/notebook/contact_detail.html
{% extends "notebook/base.html" %}
{% block title %}Contact detail{% endblock title %}
{% block content %}
  <ul>
    <li><strong>First name :</strong> {{ contact.first_name }}</li>
    <li><strong>Last name :</strong> {{ contact.last_name }}</li>
    <li><strong>Birthday :</strong> {{ contact.birthday|date:"SHORT_DATE_FORMAT" }}</li>
    {% if emails %}
      <li><strong>Emails:</strong><ul>
      {% for email in emails %}
        <li>{{ email.email }}</li>
      {% endfor %}
      </ul></li>
    {% endif %}
  </ul>
{% endblock content %}

djanglavel/notebook/templates/notebook/contact_form.html
{% extends "notebook/base.html" %}{% load bootstrap3 %}
{% block title %}Contact form{% endblock title %}
{% block content %}
<form action="{% url 'notebook:create' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Submit
    </button>
  {% endbuttons %}
</form>
{% endblock content %}

djanglavel/notebook/templates/notebook/contact_list.html
{% extends "notebook/base.html" %}{% load bootstrap3 %}
{% block title %}Contact list{% endblock title %}
{% block content %}
<p>
  <a href="{% url 'notebook:create' %}" class="btn btn-default">
    <span class="glyphicon glyphicon-plus"></span>New contact
  </a>
</p>
{% if contacts %}
  <ul>
  {% for contact in contacts %}
    <li>
      <a href="{% url 'notebook:update' slug=contact.slug %}" class="btn btn-warning">
        <span class="glyphicon glyphicon-pencil"></span>
      </a>
      <a href="{% url 'notebook:delete' slug=contact.slug %}" class="btn btn-danger">
        <span class="glyphicon glyphicon-trash"></span>
      </a>
      <a href="{% url 'notebook:detail' slug=contact.slug %}">{{ contact.get_full_name }}</a>
    </li>
  {% endfor %}
  </ul>
{% else %}
  <p>No Contacts.</p>
{% endif %}
{% endblock content %}

djanglavel/notebook/templates/notebook/index.html
{% extends "notebook/base.html" %}
{% block title %}Contact list{% endblock title %}
{% block content %}
{% if contacts %}
  <ul>
  {% for contact in contacts %}
    <li>
      <ul>
        <li><strong>First name :</strong> {{ contact.first_name }}</li>
        <li><strong>Last name :</strong> {{ contact.last_name }}</li>
        <li><strong>Birthday :</strong> {{ contact.birthday|date:"SHORT_DATE_FORMAT" }}</li>
      </ul>
    </li>
  {% endfor %}
  </ul>
{% else %}
  <p>No Contacts.</p>
{% endif %}
{% endblock content %}